---
# yamllint disable rule:line-length
# $schema https://raw.githubusercontent.com/megalinter/megalinter/main/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
# ~/.mega-linter.yml
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/configuration/ and in linters documentation

## FILTERS ##

# FILTER_REGEX_EXCLUDE: "\
# (?ix)(\
# |megalinter-reports/.*\
# |\\.git/.*\
# )$"

# quiets validation errors
YAML_V8R_FILTER_REGEX_EXCLUDE: "\\.github/workflows/(docs|labeller-file-based|labels)\\.yaml"

## CONVERT ERRORS TO WARNINGS ##

# quiets validation errors
ACTION_ACTIONLINT_DISABLE_ERRORS: true

# quiets validation errors
ACTION_ACTIONLINT_ARGUMENTS: >
  -ignore 'property "workflow_update_github_pat" is not defined in .+'

# quiets validation errors
POWERSHELL_POWERSHELL_DISABLE_ERRORS: true

# quiets validation errors
PYTHON_BANDIT_DISABLE_ERRORS: true
# or quiet completely:
# PYTHON_BANDIT_ARGUMENTS: "--skip B101,B404,B603"

# quiets validation errors
PYTHON_PYLINT_DISABLE_ERRORS: true
# or quiet completely:
# PYTHON_PYLINT_ARGUMENTS: "--disable import-error"

# quiets validation errors
REPOSITORY_CHECKOV_DISABLE_ERRORS: true
# or quiet completely:
# REPOSITORY_CHECKOV_ARGUMENTS: "--skip-check CKV2_GHA_1,CKV_GHA_7"

# quiets validation errors
#   fatal: detected dubious ownership in repository at '/github/workspace/.git'
REPOSITORY_DEVSKIM_DISABLE_ERRORS: true

## COMMAND ARGUMENTS ##

# REPOSITORY_DEVSKIM_ARGUMENTS:
#   - '--ignore-globs'
#   - '**/megalinter-reports/**,**/.git/**'

## GLOBAL SETTINGS ##

APPLY_FIXES: all
# Quiet logs:
# [GitHub Status Reporter] Error posting Status for JSONwith prettier: 403
# GitHub API response: {"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/commits/statuses#create-a-commit-status"}
# GITHUB_STATUS_REPORTER: true
# LOG_LEVEL: DEBUG
PRINT_ALL_FILES: true
PRINT_ALPACA: false
# Quiet logs:
#   WARNING: there is a new pyright version available (v1.1.270 -> v1.1.281).
#   Please install the new version or set PYRIGHT_PYTHON_FORCE_VERSION to `latest`
# but causes schema to fail validation:
# PYRIGHT_PYTHON_FORCE_VERSION: 'latest'
SHOW_ELAPSED_TIME: true
